### ISSUE TITLE
Webview is opening instead of Play Store.

### ISSUE THREAD

**Issue by tech-instacare** [larryaasen/upgrader#178] opened 2022-05-23 13:29 UTC
Debug Logs: 
```
I/flutter (29815): upgrader: instantiated.
I/flutter (29815): upgrader: build UpgradeAlert
I/flutter (29815): upgrader: languageCode: en
I/flutter (29815): upgrader: default operatingSystem: android RMX2030EX_11_C.79
I/flutter (29815): upgrader: operatingSystem: android
I/flutter (29815): upgrader: platform: TargetPlatform.android
I/flutter (29815): upgrader: isAndroid: true, isIOS: false, isLinux: false, isMacOS: false, isWindows: false, isFuchsia: false, isWeb: false
I/flutter (29815): upgrader: package info packageName: attrayant.design.pat.instacare
I/flutter (29815): upgrader: package info appName: InstaCare
I/flutter (29815): upgrader: package info version: 3.4.1
I/flutter (29815): upgrader: appcast is available for this platform
I/flutter (29815): upgrader: appcast item count: 1
I/flutter (29815): upgrader: appcast best item version: 3.4.2
I/flutter (29815): upgrader: appcast item count: 1
I/flutter (29815): upgrader: appcast best item version: 3.4.2
I/flutter (29815): upgrader: blocked: true
I/flutter (29815): upgrader: debugDisplayAlways: false
I/flutter (29815): upgrader: debugDisplayOnce: false
I/flutter (29815): upgrader: hasAlerted: false
I/flutter (29815): upgrader: appStoreVersion: 3.4.2
I/flutter (29815): upgrader: installedVersion: 3.4.1
I/flutter (29815): upgrader: minAppVersion: null
I/flutter (29815): upgrader: isUpdateAvailable: true
I/flutter (29815): upgrader: shouldDisplayUpgrade: true
I/flutter (29815): upgrader: shouldDisplayReleaseNotes: true
I/flutter (29815): upgrader: showDialog title: Update App?
I/flutter (29815): upgrader: showDialog message: A new version of InstaCare is available! Version 3.4.2 is now available-you have 3.4.1.
I/flutter (29815): upgrader: showDialog releaseNotes: Release Notes.
```

pubspec.lock file
```
  upgrader:
    dependency: "direct main"
    description:
      name: upgrader
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.0"
```
When I press on Update button, it is launching webview instead of Play Store App and if I try to launch Play Store App from webview it is showing following error:
Webpage not available
The webpage at intent://play.app.goo.gl/?link=MY_APP_LINK#intent;pack could not be loaded because: net::ERR_UNKOWN_URL_SCHEME

**Comment by larryaasen** [comment] 2022-06-07 01:09
@tech-instacare @habibrosyad I am not able to reproduce this issue on Android 10 (API level 29). Some of the log you provided is missing. After the user taps the `UPDATE NOW` button, the log should display this line and some others. Can you show me that part of the log and any other upgrader log message?
```
upgrader: button tapped: update now
```
Also, what Android version does this happen on?

**Comment by azharxes** [comment] 2022-06-14 04:56
Fixed it in this, check it out @larryaasen 

https://github.com/larryaasen/upgrader/pull/185

**Comment by larryaasen** [comment] 2022-06-14 11:19
This has been fixed and released in version `4.2.2-alpha.1`. Please try it out.

**Closed by larryaasen** 2022-06-14 11:19 UTC
Labels: need more information

**Comment by larryaasen** [comment] 2022-06-24 00:05
I just released the 4.2.2 update to the [ugprader package on pub.dev](https://pub.dev/packages/upgrader/versions/4.2.2) to fix this issue.

**Comment by GledsonLScruz** [comment] 2024-04-01 11:33
Hi Guys, im with this issue in my app, i want to know how can i solve it.
upgrader version: 7.1.0
android version 12

[√] Flutter (Channel stable, 3.10.6, on Microsoft Windows [versÆo 10.0.19044.2130], locale pt-BR)
    • Flutter version 3.10.6 on channel stable at C:\Users\gledson.cruz\Documents\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f468f3366c (9 months ago), 2023-07-12 15:19:05 -0700
    • Engine revision cdbeda788a
    • Dart version 3.0.6
    • DevTools version 2.23.1

![MicrosoftTeams-image (8)](https://github.com/larryaasen/upgrader/assets/86816795/936a6924-ef75-4e02-ba3e-ac5a9c28b76d)

**Comment by larryaasen** [comment] 2024-04-01 11:39
@GledsonLScruz This issue is closed. Can you open a new one?
