### ISSUE TITLE
I don't know why when I build apk ,is not working!

### ISSUE THREAD

**Issue by 8108905** [larryaasen/upgrader#81] opened 2021-01-04 22:12 UTC
The "emulator" is valid;
Only the apk was built, and I tried various methods! It still doesn't work!
Finally, I tried to download your "sample" and still the same problem!

**Comment by 8108905** [comment] 2021-01-04 22:12
Launching lib/main.dart on MI 9 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY .
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...
Waiting for MI 9 to report its views...
Debug service listening on ws://127.0.0.1:65063/n1eCyj5MKmo=/ws
Syncing files to device MI 9...
I/flutter (15825): upgrader: build UpgradeAlert
I/flutter (15825): upgrader: package info packageName: com.google.maps
I/flutter (15825): upgrader: package info version: 1.0.0
I/flutter (15825): upgrader: appcast is available for this platform
I/flutter (15825): upgrader: appcast item count: 4
I/flutter (15825): upgrader: appcast best item version: 5.0
I/flutter (15825): upgrader: blocked: false
I/flutter (15825): upgrader: debugDisplayAlways: false
I/flutter (15825): upgrader: debugDisplayOnce: false
I/flutter (15825): upgrader: hasAlerted: false
I/flutter (15825): upgrader: appStoreVersion: 5.0
I/flutter (15825): upgrader: installedVersion: 1.0.0
I/flutter (15825): upgrader: minAppVersion: null
I/flutter (15825): upgrader: isUpdateAvailable: true
I/flutter (15825): upgrader: shouldDisplayUpgrade: true
E/flutter (15825): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The method 'replaceAll' was called on null.
E/flutter (15825): Receiver: null
E/flutter (15825): Tried calling: replaceAll("{{appName}}", "upgrader_example")
E/flutter (15825): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
E/flutter (15825): #1      Upgrader.message (package:upgrader/src/upgrader.dart:258:15)
E/flutter (15825): #2      Upgrader.checkVersion.<anonymous closure> (package:upgrader/src/upgrader.dart:278:24)
E/flutter (15825): #3      new Future.delayed.<anonymous closure> (dart:async/future.dart:326:39)
E/flutter (15825): #4      _rootRun (dart:async/zone.dart:1182:47)
E/flutter (15825): #5      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (15825): #6      _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (15825): #7      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
E/flutter (15825): #8      _rootRun (dart:async/zone.dart:1190:13)
E/flutter (15825): #9      _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (15825): #10     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
E/flutter (15825): #11     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (15825): #12     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
E/flutter (15825): #13     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
E/flutter (15825): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter (15825): 
I/com.google.map(15825): ProcessProfilingInfo new_methods=401 is saved saved_to_disk=1 resolve_classes_delay=8000

**Comment by larryaasen** [comment] 2021-01-08 04:03
I think the problem is related to the languageCode in class `UpgraderMessages()`. Can you look at the value for messages.languageCode and see what that contains? It should be set to `en` or the locale language code.

**Comment by 8108905** [comment] 2021-01-10 21:15
I try do    upgrader: ^2.8.0 ; then copy 'https://github.com/larryaasen/upgrader/blob/master/example/lib/main.dart' , still some problem , AVD is good; when I ' flutter build apk ' install to my phone , still some problem!

**Comment by larryaasen** [comment] 2021-01-10 22:17
@8108905 Can you share the latest debug log with the languageCode?

**Comment by 8108905** [comment] 2021-01-11 04:28
sorry, I do not know! How to use languageCode to check the latest debug log?

First step: download  'https://github.com/larryaasen/upgrader ';
Second step:  run 'upgrader/example/lib/main.dart'; 
Third step : run Android emulator is good ! 
Fourth step:'flutter build apk';
Fifth step: install my phone ,just show checking ! no any Alert! 
Sixth step: I turn on the developer mode on my phone, connect to the computer and run main.dart, still show same log!

You can follow my steps and try it on a real phone! I don’t know why other users have not encountered this problem? Or is it just running on the simulator?


Thank you very much for your reply !

**Comment by larryaasen** [comment] 2021-01-11 12:32
There should be a line in the debug log that shows the language code like this:

`upgrader: languageCode: en`

Can you share that line?

Also, I have updated this package again to include more debug logging to help better understand this problem. Please try version `2.8.1` this time. If you can share all of your upgrader log again that would be helpful.

**Comment by 8108905** [comment] 2021-01-11 18:44
finally, I understand! My phone language is zh'; when I change my phone language to English,everything is back to normal  
Please add zh language support ！
thank you very much for your help！

**Comment by larryaasen** [comment] 2021-01-12 03:45
I just published version 2.8.2 with a fix for this problem. It now defaults to 'en' (English) when it detects an unknown language code.  Thanks for working with me to resolve this.
If you would like to submit a translation for `zh` please add the strings to this issue https://github.com/larryaasen/upgrader/issues/37, and I will incorporate it into the package.

**Closed by larryaasen** 2021-01-12 03:45 UTC
Labels: need more information
